# -*- coding: utf-8 -*-
"""
CS437/CS5317/EE414/EE513 Deep Learning Programming Assignment 3
Part 3: Generative Adversarial Network (GAN) with Latent Space Interpolation
"""

# <span style="color: #9370DB;">**Submission Guidelines**</span>

- <span style="color: #9370DB;">Please rename the file to `<RollNumber>_PA3_3`.</span>
- <span style="color: #9370DB;">Please also submit a **.py** file of every Notebook. You can do this by exporting your **ipynb** to a Python script.</span>
- <span style="color: #9370DB;">Please submit a zipped folder of both your Jupyter Notebooks and Python script files.</span>
- <span style="color: #9370DB;">PLEASE RUN ALL CELLS 🙏🏻.</span>

### Name:
### Roll Number:

# Part 1: GANs with Latent space interpolation

In this part of the assignment, you'll implement a Generative Adversarial Network (GAN) to:
- Generate images resembling handwritten digits from the MNIST dataset.
- Explore latent space interpolation between two images by transioning from one digit to another.
- Generate a few images of your own and perform some mathematical operations with them in the latent space to see what sort of output you can come up with.

[All code blocks should already have been run and the outputs should be visible in order to be graded]

### Imports
"""

# ============ Import stuff here =============
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import torchvision.utils as vutils
import matplotlib.pyplot as plt
import numpy as np
device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
# ===== you may include more helper libs ======
from torch.utils.data import DataLoader, random_split
# ===== (just don't include an entire =========
# ===== generator/discriminator - that ========
# ===== you've to make from scratch) ==========

"""### Load the MNIST thing

In this section:
- Load the MNIST dataset
- Transform/pre-process the dataset (if required)
- Define your test-train split
- Use dataloader to load stuff
- Print the split ratio AND visualize some of the digits (along with the labels)
"""

# Code here
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

dataset = datasets.MNIST(root="./data", train=True, transform=transform, download=True)

train_size = int(0.8 * len(dataset))  # 80% training data
test_size = len(dataset) - train_size  # 20% test data
train_dataset, test_dataset = random_split(dataset, [train_size, test_size])
batch_size = 64
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print(f"Training set size: {len(train_dataset)}")
print(f"Test set size: {len(test_dataset)}")

def show_samples(dataset, num_samples=6):
    fig, axes = plt.subplots(1, num_samples, figsize=(10, 2))
    for i in range(num_samples):
        image, label = dataset[i]
        axes[i].imshow(image.squeeze(), cmap="gray")
        axes[i].set_title(f"Label: {label}")
        axes[i].axis("off")
    plt.show()
show_samples(train_dataset)

"""## Make your GANg
![pic.png](attachment:pic.png)

Basic GAN structure is show above. GANs have two componenets:

**Generator (G):** Takes a random noise vector ($z$) as input and generates synthetic image $G(z)$ i.e., an output that aims to resemble real data.
**Discriminator (D):** Acts as a binary classifier that distinguishes between real and fake image. It is trained to correctly identify whether an input is real (from the dataset) or fake (generated by G).

They both compete with each other. The generator tries to fool the discriminator, while the discriminator tries to improve its ability to detect fakes. This adversarial process helps the generator produce increasingly realistic outputs.
"""

# Code the Generator here
class Generator(nn.Module):
    def __init__(self, latent_dim=64, img_shape=(1,28,28)):
        super(Generator, self).__init__()
        self.img_shape = img_shape
        out_features = 1
        for dim in img_shape:
            out_features *= dim
        self.model = nn.Sequential(
            nn.Linear(latent_dim, 256),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Linear(256, 256),
            nn.BatchNorm1d(256),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Linear(256, 512),
            nn.BatchNorm1d(512),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Linear(512, out_features),
            nn.Tanh()
        )

    def forward(self, z):
        out = self.model(z)
        out = out.view(out.size(0), *self.img_shape)
        return out

# Code the Discriminator here
class Discriminator(nn.Module):
    def __init__(self, img_shape=(1,28,28)):
        super(Discriminator, self).__init__()
        in_features = 1
        for dim in img_shape:
            in_features *= dim
        self.model = nn.Sequential(
            nn.Linear(in_features, 512),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Dropout(0.3),

            nn.Linear(512, 256),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Dropout(0.3),

            nn.Linear(256, 64),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, img):
        batch_size = img.size(0)
        flattened = img.view(batch_size, -1)
        validity = self.model(flattened)
        return validity

# initializing the instances of the Generator and Discriminator respectively
latent_dim = 64
img_shape = (1, 28, 28)

generator = Generator(latent_dim=latent_dim, img_shape=img_shape)
discriminator = Discriminator(img_shape=img_shape)

"""### Losses and optimizers"""

# Loss
criterion = nn.BCELoss()

# Optimizers
optimizer_g = optim.Adam(generator.parameters(), lr=0.0002)
optimizer_d = optim.Adam(discriminator.parameters(), lr=0.0002)

"""## Training Loop
Now we have to load the data (preprocess it or do some image augmentation if you need) and train the model.

Lets have brief look at how the loop for a vanilla GAN looks like, and then you can implement it yourself.

Each epoch involves a couple of steps:
1. Prep some data both fake and real
2. Train the discriminator with some real data (real loss)
3. Train the discriminator with some fake data (fake loss)
4. Train the generator (generator loss)

details about losses is below

**Discriminator**
The discriminator is trained to distinguish between real and fake images (binary classification). It aims to correctly classify real images as real and generated images as fake. It has two components:
- Real Loss: Measures how well the discriminator classifies real images correctly.
- Fake Loss: Measures how well the discriminator identifies fake images. <br> <br>
The total discriminator loss is given by: <br>
$ L_{D} =$ real loss $+$ fake loss <br>
where <br>
real loss $= E_{x}\log(D(x))$ <br>
fake loss $= E_{z}\log(1-D(G(z)))$

**Generator**
The generator tries to fool the discriminator by generating images that D misclassifies as real. Instead of minimizing the difference between generated and real images directly, G is trained to maximize the likelihood that $D$ assigns high probability to fake images (so it'll only have the maximizing portion) <br><br>
$ L_{G} = E\log(D(G(z)))$  <br>
"""

epochs = 0
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
generator.to(device)
discriminator.to(device)
# Training Loop
epochs = 50  # set this higher to train longer

G_losses, D_losses = [], []
best_g_loss = float('inf')
best_d_loss = float('inf')

for epoch in range(epochs):
    epoch_d_loss = 0.0
    epoch_g_loss = 0.0

    for i, (real_imgs, _) in enumerate(train_loader):
        real_imgs = real_imgs.to(device)
        batch_size = real_imgs.size(0)
        discriminator.zero_grad()
        real_labels = torch.ones(batch_size, 1, device=device)
        fake_labels = torch.zeros(batch_size, 1, device=device)
        outputs_real = discriminator(real_imgs)
        d_loss_real = criterion(outputs_real, real_labels)
        z = torch.randn(batch_size, latent_dim, device=device)
        fake_imgs = generator(z)

        outputs_fake = discriminator(fake_imgs.detach())
        d_loss_fake = criterion(outputs_fake, fake_labels)
        d_loss = d_loss_real + d_loss_fake
        d_loss.backward()
        optimizer_d.step()
        generator.zero_grad()
        outputs_fake_for_g = discriminator(fake_imgs)
        g_loss = criterion(outputs_fake_for_g, real_labels)

        g_loss.backward()
        optimizer_g.step()

        epoch_d_loss += d_loss.item()
        epoch_g_loss += g_loss.item()
    epoch_d_loss /= len(train_loader)
    epoch_g_loss /= len(train_loader)

    G_losses.append(epoch_g_loss)
    D_losses.append(epoch_d_loss)

    print(f"Epoch [{epoch+1}/{epochs}] | D_loss: {epoch_d_loss:.4f} | G_loss: {epoch_g_loss:.4f}")
    if epoch_g_loss < best_g_loss:
        best_g_loss = epoch_g_loss
        torch.save(generator.state_dict(), "generator.pth")
    if epoch_d_loss < best_d_loss:
        best_d_loss = epoch_d_loss
        torch.save(discriminator.state_dict(), "discriminator.pth")

"""### Display stats
1. Save the best generator and discriminator (as `generator.pth` and `discriminator.pth` respectively).
2. Plot disc and gen losses.
3. Visualize an image from the best generator.
"""

best_generator = Generator(latent_dim=latent_dim, img_shape=img_shape).to(device)
best_generator.load_state_dict(torch.load("generator.pth"))
best_generator.eval()
latent_vector = torch.randn(1, latent_dim, device=device)

with torch.no_grad():
    gen_image = best_generator(latent_vector).cpu()
gen_image = 0.5 * (gen_image + 1.0)
gen_image_2d = gen_image.squeeze()
plt.figure(figsize=(4,4))
plt.axis("off")
plt.title("Single Generated Image")
plt.imshow(gen_image_2d.numpy(), cmap="gray")
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
plt.plot(G_losses, label='Generator Loss')
plt.plot(D_losses, label='Discriminator Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Generator and Discriminator Loss During Training')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig('loss_plot.png')
plt.show()

"""### Latent space interpolation with MNIST
The latent space is the space of all possible inputs that the generator can take, and it is a vector space, and since it is a vector space we can do some vector operations on it, such as interpolation, which is what we will be doing here.
To read up more on this, you can visit the following link: https://machinelearningmastery.com/how-to-interpolate-and-perform-vector-arithmetic-with-faces-using-a-generative-adversarial-network/

Things to do:
1. Define two random noises of some latent dimensions.
2. Generate images by interpolating from one noise to the other. You can use the following formula as a reference:  
   
   $$
   \text{interpolation} = \alpha \cdot z_1 + (1-\alpha) \cdot z_2
   $$  

   where  $z_{1}$ and $z_{2}$ are two random noises in the latent space. the result here should be a series of images that show how the generator is transitioning from one image to another; such as, how it goes from an image of 3 to an image of 7 for example.

3. Visualize/plot the interpolated generation.

(please make sure that there are atleast 10 steps, including the final and starting images and you visualize all 10 steps)
"""

# code here
import torch
import matplotlib.pyplot as plt

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

latent_dim = 64
num_steps = 10
z1 = torch.randn(1, latent_dim, device=device)
z2 = torch.randn(1, latent_dim, device=device)

interpolated_images = []

for i in range(num_steps):
    alpha = i / (num_steps - 1)
    z_interpolated = (1 - alpha)*z1 + alpha*z2

    with torch.no_grad():
        img = best_generator(z_interpolated).cpu()
    img = 0.5 * (img + 1.0)
    img_2d = img.squeeze(0).squeeze(0).numpy()

    interpolated_images.append(img_2d)
fig, axes = plt.subplots(1, num_steps, figsize=(2*num_steps, 2))
for i, ax in enumerate(axes):
    ax.imshow(interpolated_images[i], cmap='gray')
    ax.set_title(f"Step {i}")
    ax.axis("off")

plt.suptitle("Latent Space Interpolation (MNIST)")
plt.tight_layout()
plt.show()

"""### Latent space interpolation with pre-trained CelebA
`CelebA` dataset contains ~200,000 images of 178×218 consisting of celebrity faces. Luckily, you don't have to train your GAN over this cuz we're providing you with the pretrained model (and template code to load it). You can download the pre-trained generator from [here](https://pern-my.sharepoint.com/:f:/g/personal/24100238_lums_edu_pk/Eumg8ej04zBJigkuymRYz9MBFRscbETu-NzdzA6tsvYQPQ?e=50uaWN). There's also a `dcgan.py` file (that you're supposed to put in the current directory).

In this section, you're supposed to perform latent space interpolation just like you did with MNIST. Your  output should look smth like this:
![image.png](attachment:image.png)
(a smiling woman interpolated to a neutral man)
"""

import shutil
import os
print(os.listdir())

# put the dcgan.py file and generator.pt in the current directory and then run this cell
from dcgan import DCGAN
generator_path = "generator.pt"
gan = DCGAN(gan_type="gan", use_cuda=True)
gan.load_model(filename=generator_path, use_cuda=torch.cuda.is_available())
gan.eval()
gan = gan.to(device)
print("Number of parameters in the pre-trained generator:", gan.get_num_params())

'''
TODO:
1- Visualize the images generated from z1 and z2
2- Interpolate from z1 to z2 (using the formula given above) and
   plot all interpolation (just like the given example). This task
   is more or less similar to the one you did with MNIST.
3- Make sure interpolation has minimum of 10 steps.
'''

# ====== Your code below ========
import torch
import matplotlib.pyplot as plt
import numpy as np


generator_path = "generator.pt"
gan = DCGAN(gan_type="gan", use_cuda=torch.cuda.is_available())
gan.load_model(filename=generator_path, use_cuda=torch.cuda.is_available())
gan.eval()
gan = gan.to(device)

print("Number of parameters in the pre-trained generator:", gan.get_num_params())
latent_dim = 100
z1 = torch.randn(1, latent_dim, device=device)
z2 = torch.randn(1, latent_dim, device=device)
num_steps = 30
interpolated_images = []

for i in range(num_steps):
    alpha = i / (num_steps - 1)
    z_interpolated = (1 - alpha) * z1 + alpha * z2

    with torch.no_grad():
        img = gan.generate_img(z_interpolated).cpu().squeeze()

    img = img.permute(1, 2, 0)
    img = (img + 1) / 2

    interpolated_images.append(img.numpy())
fig, axes = plt.subplots(1, num_steps, figsize=(2 * num_steps, 2))

for i, img in enumerate(interpolated_images):
    axes[i].imshow(img)
    axes[i].axis("off")
    axes[i].set_title(f"Step {i}")

plt.suptitle("Latent Space Interpolation (CelebA)")
plt.show()

# ====== Your code above ========

"""### Vector arithmatic in the latent space
Since issa vector space, you can perform arithmatics (such as subtraciton, addition etc.)
<br>

When interpolating between two celebA images in the latent space, you might notice that the transition sometimes passes through representations of other facial expressions/genders. If you see the example above, while morphing from a smiling woman to a neutral man, the image briefly resembles a neutral woman. This happens because the latent space captures underlying features of the dataset, and the interpolation path can traverse regions where features of both numbers mix.

This concept extends to arithmetic in the latent space—adding/subtracting two (or more) latent vectors can produce meaningful blends of their features. For instance, adding the representation of a black person and a white person might generate a brown person.

Now, in this section, you're supposed to perform the following tasks:
1. Generate two (or more) images.
2. Perform some arithmetic on their latent space vectors and then generate the image from the resultant.
3. Display the results. <br>

### Example:
1.  $\text{random\_noise}_1$  generates $\text{generated\_image}_1$, and  
   $\text{random\_noise}_2$ generates $\text{generated\_image}_2$.
   You can save your noises as `.pt` file using `torch.save()`.
2. Compute the new latent vector:  
   $\text{random\_noise}_r$ = $\text{random\_noise}_1$ + $\text{random\_noise}_2$
3. Generate an image from $\text{random\_noise}_r$, denoted as $\text{generated\_image}_r$.
4. Display the results and check if:  
   $\text{generated\_image}_r$ = $\text{generated\_image}_1$ + $\text{generated\_image}_2$

Repeat this for at least three different pairs of images (with diff arithmetics).

Note: the arithematic results won't be perfect but to some extent would make sense.
"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
generator = DCGAN(gan_type='gan', latent_dim=100).to(device)
generator.load_model("generator.pt", use_cuda=torch.cuda.is_available())
num_images = 100
latent_vectors = torch.randn(num_images, 100, device=device)
with torch.no_grad():
    generated_images = generator.generate_img(latent_vectors)
images = generated_images.cpu().numpy()
images = np.transpose(images, (0, 2, 3, 1))
images = (images + 1) / 2.0
fig, axes = plt.subplots(10, 10, figsize=(20, 20))
for i, ax in enumerate(axes.flat):
    ax.imshow(images[i])
    ax.axis('off')
    ax.set_title(f"{i}", fontsize=8, y=-0.15)
plt.tight_layout()
plt.show()
torch.save(latent_vectors, 'latent_vectors.pt')

generator.eval()
latent_vectors = torch.load('latent_vectors.pt', map_location=device)
z73 = latent_vectors[73]
z75 = latent_vectors[75]
result_vector =z73 + z75
torch.save(result_vector.cpu(), 'added_vector_73_75.pt')
def show_image(z, title, ax):
    with torch.no_grad():
        img = generator.generate_img(z.unsqueeze(0)).cpu().squeeze()
    img = (img.permute(1, 2, 0).numpy() + 1) / 2
    ax.imshow(img)
    ax.set_title(title)
    ax.axis('off')

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
show_image(z73, "Image 73", axes[0])
show_image(z75, "Image 75", axes[1])
show_image(result_vector, "73 + 75 Result", axes[2])
plt.tight_layout()
plt.show()

generator.eval()
latent_vectors = torch.load('latent_vectors.pt', map_location=device)
z_smile1 = latent_vectors[4]
z_neutral = latent_vectors[43]
smile_direction = 0.5 * z_smile1 - z_neutral
result_vector = z_neutral + 0.775* smile_direction
def show_images():
    fig, axes = plt.subplots(1, 3, figsize=(20, 5))

    titles = ["Smile 1 (23)",  "Neutral Man (43)", "Result: Smiling Man"]
    vectors = [z_smile1, z_neutral, result_vector]

    for ax, vec, title in zip(axes, vectors, titles):
        with torch.no_grad():
            img = generator.generate_img(vec.unsqueeze(0)).cpu().squeeze()
        img = (img.permute(1, 2, 0).numpy() + 1)/2
        ax.imshow(img)
        ax.set_title(title)
        ax.axis('off')

    plt.tight_layout()
    plt.show()

show_images()
torch.save(result_vector.cpu(), 'smiling_man_result.pt')

generator.eval()
latent_vectors = torch.load('latent_vectors.pt', map_location=device)
z_smiling = latent_vectors[32]
z_hat = latent_vectors[31]
result_vector = 0.5*z_neutral + 0.5*z_smiling
def show_images():
    fig, axes = plt.subplots(1, 3, figsize=(20, 5))

    titles = ["Glasses Face (55)", "Neutral Face (43)", "Result: Neutral + Glasses"]
    vectors = [z_smiling, z_neutral, result_vector]

    for ax, vec, title in zip(axes, vectors, titles):
        with torch.no_grad():
            img = generator.generate_img(vec.unsqueeze(0)).cpu().squeeze()
        img = (img.permute(1, 2, 0).numpy() + 1) / 2
        ax.imshow(img)
        ax.set_title(title)
        ax.axis('off')

    plt.tight_layout()
    plt.show()

show_images()

"""## ANALYTICAL QUESTIONS

**Q1:** You see some of the generated images are distorted or sorta unrealistic. What major problem do you think GANs have that's causing this distortion? <br><br>
**Ans** (keep it very brief and preferably make bullet points):

1)since gans aim for nash equilibrium where ones loss is others benefit,this can lead to instability in outputs.

2)mode collapse can lead to limited variations which is why we see distorted outputs or some repetitions.

3)GANs do not explicitly model the spatial or semantic structure of images, leading to odd artifacts (e.g blurry edges).

You may have look over [here](https://aurorasolar.com/blog/putting-ai-to-the-test-generative-adversarial-networks-vs-diffusion-models/) how diffusion models intriduced realism in the image generations (as compared to the GANs)
"""